# SPDX-License-Identifier: MIT
# Copyright (c) 2021-2022 Tano Systems LLC. All rights reserved.

header:
  version: 11
  includes:
    - kas/layers/meta-python.yml
    - kas/layers/meta-perl.yml

repos:
  meta-security:
    url: git://git.yoctoproject.org/meta-security

# local_conf_header:
#   security: |
#     DISTRO_FEATURES:append = " apparmor"

